#ifndef __INTERNGL_H__
#define __INTERNGL_H__


#include "gl/glext.h"
#include "gl/wglext.h"


#ifndef INTERNGL_H_PREFIX
#define INTERNGL_H_PREFIX extern
#define INTERNGL_H_POSTFIX
#endif


/* GL_ARB_vertex_buffer_object */
INTERNGL_H_PREFIX PFNGLBINDBUFFERARBPROC           glBindBufferARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLDELETEBUFFERSARBPROC        glDeleteBuffersARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGENBUFFERSPROC              glGenBuffersARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLISBUFFERARBPROC             glIsBufferARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLBUFFERDATAARBPROC           glBufferDataARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLBUFFERSUBDATAARBPROC        glBufferSubDataARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGETBUFFERSUBDATAARBPROC     glGetBufferSubDataARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMAPBUFFERARBPROC            glMapBufferARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLUNMAPBUFFERARBPROC          glUnmapBufferARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGETBUFFERPARAMETERIVARBPROC glGetBufferParameterivARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGETBUFFERPOINTERVARBPROC    glGetBufferPointervARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLDELETEBUFFERSPROC           glDeleteBuffers INTERNGL_H_POSTFIX;

/* GL_ARB_multitexture */
INTERNGL_H_PREFIX PFNGLACTIVETEXTUREARBPROC        glActiveTextureARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLCLIENTACTIVETEXTUREARBPROC  glClientActiveTextureARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD1DARBPROC      glMultiTexCoord1dARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD1DVARBPROC     glMultiTexCoord1dvARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD1FARBPROC      glMultiTexCoord1fARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD1FVARBPROC     glMultiTexCoord1fvARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD1IARBPROC      glMultiTexCoord1iARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD1IVARBPROC     glMultiTexCoord1ivARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD1SARBPROC      glMultiTexCoord1sARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD1SVARBPROC     glMultiTexCoord1svARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD2DARBPROC      glMultiTexCoord2dARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD2DVARBPROC     glMultiTexCoord2dvARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD2FARBPROC      glMultiTexCoord2fARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD2FVARBPROC     glMultiTexCoord2fvARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD2IARBPROC      glMultiTexCoord2iARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD2IVARBPROC     glMultiTexCoord2ivARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD2SARBPROC      glMultiTexCoord2sARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD2SVARBPROC     glMultiTexCoord2svARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD3DARBPROC      glMultiTexCoord3dARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD3DVARBPROC     glMultiTexCoord3dvARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD3FARBPROC      glMultiTexCoord3fARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD3FVARBPROC     glMultiTexCoord3fvARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD3IARBPROC      glMultiTexCoord3iARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD3IVARBPROC     glMultiTexCoord3ivARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD3SARBPROC      glMultiTexCoord3sARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD3SVARBPROC     glMultiTexCoord3svARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD4DARBPROC      glMultiTexCoord4dARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD4DVARBPROC     glMultiTexCoord4dvARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD4FARBPROC      glMultiTexCoord4fARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD4FVARBPROC     glMultiTexCoord4fvARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD4IARBPROC      glMultiTexCoord4iARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD4IVARBPROC     glMultiTexCoord4ivARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD4SARBPROC      glMultiTexCoord4sARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLMULTITEXCOORD4SVARBPROC     glMultiTexCoord4svARB INTERNGL_H_POSTFIX;

/* Shaders */
INTERNGL_H_PREFIX PFNGLATTACHSHADERPROC       glAttachShader      INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation  INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLCOMPILESHADERPROC      glCompileShader     INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLCREATEPROGRAMPROC      glCreateProgram     INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLCREATESHADERPROC       glCreateShader      INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLDELETEPROGRAMPROC      glDeleteProgram     INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLDELETESHADERPROC       glDeleteShader      INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLDETACHSHADERPROC       glDetachShader      INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLISPROGRAMPROC          glIsProgram         INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLISSHADERPROC           glIsShader          INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLLINKPROGRAMPROC        glLinkProgram       INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLSHADERSOURCEPROC       glShaderSource      INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLUSEPROGRAMPROC         glUseProgram        INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLUNIFORM1FPROC          glUniform1f         INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLUNIFORM1IPROC          glUniform1i         INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLUNIFORM2FPROC          glUniform2f         INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLUNIFORM3FPROC          glUniform3f         INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLUNIFORM4FPROC          glUniform4f         INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLUNIFORM4FPROC          glUniform4fv        INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLUNIFORMMATRIX4FVPROC   glUniformMatrix4fv  INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLVERTEXATTRIB1FPROC     glVertexAttrib1f    INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLVERTEXATTRIB2FPROC     glVertexAttrib2f    INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLVERTEXATTRIB3FPROC     glVertexAttrib3f    INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLVERTEXATTRIB4FPROC     glVertexAttrib4f    INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGETOBJECTPARAMETERFVARBPROC  glGetObjectParameterfvARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGETOBJECTPARAMETERIVARBPROC  glGetObjectParameterivARB INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGETINFOLOGARBPROC      glGetInfoLogARB     INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGETSHADERIVPROC        glGetShaderiv       INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGETSHADERINFOLOGPROC   glGetShaderInfoLog  INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation            INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGENBUFFERSPROC         glGenBuffers        INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLBINDBUFFERPROC         glBindBuffer        INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLBUFFERDATAPROC         glBufferData        INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGENVERTEXARRAYSPROC    glGenVertexArrays   INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLBINDVERTEXARRAYPROC    glBindVertexArray   INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays  INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLACTIVETEXTUREPROC      glActiveTexture     INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLGETATTRIBLOCATIONPROC  glGetAttribLocation INTERNGL_H_POSTFIX;


/* WGL_EXT_swap_control */
INTERNGL_H_PREFIX PFNWGLSWAPINTERVALEXTPROC   wglSwapIntervalEXT  INTERNGL_H_POSTFIX;

/* WGL_EXT_extensions_string */
INTERNGL_H_PREFIX PFNWGLGETEXTENSIONSSTRINGARBPROC wglGetExtensionsStringARB INTERNGL_H_POSTFIX;

/* Frame buffer object */
INTERNGL_H_PREFIX PFNGLGENFRAMEBUFFERSPROC    glGenFramebuffers   INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLBINDFRAMEBUFFERPROC    glBindFramebuffer   INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture          INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLFRAMEBUFFERTEXTURE2DPROC   glFramebufferTexture2D    INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus  INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers          INTERNGL_H_POSTFIX;
INTERNGL_H_PREFIX PFNGLDRAWBUFFERSPROC        glDrawBuffers       INTERNGL_H_POSTFIX;

#undef INTERNGL_H_PREFIX
#undef INTERNGL_H_POSTFIX

#endif
